### ISSUE TITLE
Add support for ssl self signed

### ISSUE THREAD

**Issue by williamdes** [eriksoderblom/alpine-apache-php#2]
Just add `apache2-ssl` package

But it requires to replace `DocumentRoot` in the ssl config
```

    sed -i 's#^DocumentRoot ".*#DocumentRoot "/htdocs"#g' /etc/apache2/conf.d/ssl.conf && \
    sed -i 's/#ServerName\ www.example.com:80/ServerName\ website-domain.local:8081/' /etc/apache2/conf.d/ssl.conf && \
```

**Comment by eriksoderblom** [comment]
I have added this, but I chose to go with `ServerName www.example.com:443` instead of `ServerName website-domain.local:8081` from your code.
If there is something I missed in the update, please let me know.
And thank you for your input! :smiley:

**Comment by williamdes** [comment]
> I have added this, but I chose to go with `ServerName www.example.com:443` instead of `ServerName website-domain.local:8081` from your code.
> If there is something I missed in the update, please let me know.
> And thank you for your input!

Thank you !
~~Maybe add a link on the README to docker hub ;)
Or a badge maybe~~

(just had a look and it seems like the image does not exist for your account, if you want you could auto build and push it using GitHub actions)

One more nice addition would be OCI labels: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
Example: https://github.com/phpmyadmin/docker/blob/master/Dockerfile-alpine.template#L73

**Comment by eriksoderblom** [comment]
The image should be updated on docker hub now.
I used to have auto build, but docker hub removed auto build from their free plan.
I got an email that stated they would be disabled, so I removed them.
I only have this one image to maintain, and to manually build and push a few times a year is not that much work :-)

**Comment by williamdes** [comment]
> I used to have auto build, but docker hub removed auto build from their free plan.

Yeah, you can copy https://github.com/sudo-bot/gh-deployer-container/blob/main/.github/workflows/publish.yml and adjust the trigger

Basically using GitHub actions to build and push ;)


Thank you so much for all the changes, I will now use your image for my dev env 🚀

**Comment by williamdes** [comment]
By the way ENVs could be cool rather than editing the start.sh file
I can make a PR for that if you prefer

**Comment by eriksoderblom** [comment]
> By the way ENVs could be cool rather than editing the start.sh file
> I can make a PR for that if you prefer

Sure, make a PR and I will look into that.
I am looking into GitHub actions now, we'll see if I can get it to work.

**Comment by williamdes** [comment]
> > By the way ENVs could be cool rather than editing the start.sh file
> > I can make a PR for that if you prefer
> 
> Sure, make a PR and I will look into that.
> I am looking into GitHub actions now, we'll see if I can get it to work.

By the way you can copy paste workflows I have at @sudo-bot
Some are more complex and go as far as multi arch building + signing images and manifests
